//LOAD FAMILIES
export const LOAD_CLASSIFICATIONS_FAMILIES_LIST =
	'LOAD_CLASSIFICATIONS_FAMILIES_LIST';
export const LOAD_CLASSIFICATIONS_FAMILIES_LIST_SUCCESS =
	'LOAD_CLASSIFICATIONS_FAMILIES_LIST_SUCCESS';
export const LOAD_CLASSIFICATIONS_FAMILIES_LIST_FAILURE =
	'LOAD_CLASSIFICATIONS_FAMILIES_LIST_FAILURE';

