//LOAD SERIES
export const LOAD_OPERATIONS_SERIES_LIST = 'LOAD_OPERATIONS_SERIES_LIST';
export const LOAD_OPERATIONS_SERIES_LIST_SUCCESS =
	'LOAD_OPERATIONS_SERIES_LIST_SUCCESS';
export const LOAD_OPERATIONS_SERIES_LIST_FAILURE =
	'LOAD_OPERATIONS_SERIES_LIST_FAILURE';

//LOAD OPERATIONS
export const LOAD_OPERATIONS_OPERATIONS_LIST =
	'LOAD_OPERATIONS_OPERATIONS_LIST';
export const LOAD_OPERATIONS_OPERATIONS_LIST_SUCCESS =
	'LOAD_OPERATIONS_OPERATIONS_LIST_SUCCESS';
export const LOAD_OPERATIONS_OPERATIONS_LIST_FAILURE =
	'LOAD_OPERATIONS_OPERATIONS_LIST_FAILURE';

//LOAD FAMILIES
export const LOAD_OPERATIONS_FAMILIES_LIST = 'LOAD_OPERATIONS_FAMILIES_LIST';
export const LOAD_OPERATIONS_FAMILIES_LIST_SUCCESS =
	'LOAD_OPERATIONS_FAMILIES_LIST_SUCCESS';
export const LOAD_OPERATIONS_FAMILIES_LIST_FAILURE =
	'LOAD_OPERATIONS_FAMILIES_LIST_FAILURE';

//EXPORT
export const EXPORT_VARBOOK = 'EXPORT_VARBOOK';
export const EXPORT_VARBOOK_SUCCESS = 'EXPORT_VARBOOK_SUCCESS';
export const EXPORT_VARBOOK_FAILURE = 'EXPORT_VARBOOK_FAILURE';

export const LOAD_OPERATIONS_FAMILY = 'LOAD_OPERATIONS_FAMILY';
export const LOAD_OPERATIONS_SERIE = 'LOAD_OPERATIONS_SERIE';
export const LOAD_OPERATIONS_OPERATION = 'LOAD_OPERATIONS_OPERATION';
