//LOAD SERIES
export const LOAD_SERIES_LIST = 'LOAD_SERIES_LIST';
export const LOAD_SERIES_LIST_SUCCESS = 'LOAD_SERIES_LIST_SUCCESS';
export const LOAD_SERIES_LIST_FAILURE = 'LOAD_SERIES_LIST_FAILURE';
