//LOAD SERIES
export const LOAD_OPERATIONS_SERIES_LIST = 'LOAD_OPERATIONS_SERIES_LIST';
export const LOAD_OPERATIONS_SERIES_LIST_SUCCESS =
	'LOAD_OPERATIONS_SERIES_LIST_SUCCESS';
export const LOAD_OPERATIONS_SERIES_LIST_FAILURE =
	'LOAD_OPERATIONS_SERIES_LIST_FAILURE';

//LOAD OPERATIONS
export const LOAD_OPERATIONS_OPERATIONS_LIST =
	'LOAD_OPERATIONS_OPERATIONS_LIST';
export const LOAD_OPERATIONS_OPERATIONS_LIST_SUCCESS =
	'LOAD_OPERATIONS_OPERATIONS_LIST_SUCCESS';
export const LOAD_OPERATIONS_OPERATIONS_LIST_FAILURE =
	'LOAD_OPERATIONS_OPERATIONS_LIST_FAILURE';

//LOAD FAMILIES
export const LOAD_OPERATIONS_FAMILIES_LIST = 'LOAD_OPERATIONS_FAMILIES_LIST';
export const LOAD_OPERATIONS_FAMILIES_LIST_SUCCESS =
	'LOAD_OPERATIONS_FAMILIES_LIST_SUCCESS';
export const LOAD_OPERATIONS_FAMILIES_LIST_FAILURE =
	'LOAD_OPERATIONS_FAMILIES_LIST_FAILURE';

//EXPORT
export const EXPORT_VARBOOK = 'EXPORT_VARBOOK';
export const EXPORT_VARBOOK_SUCCESS = 'EXPORT_VARBOOK_SUCCESS';
export const EXPORT_VARBOOK_FAILURE = 'EXPORT_VARBOOK_FAILURE';

export const LOAD_OPERATIONS_FAMILY = 'LOAD_OPERATIONS_FAMILY';
export const LOAD_OPERATIONS_FAMILY_SUCCESS = 'LOAD_OPERATIONS_FAMILY_SUCCESS';
export const LOAD_OPERATIONS_SERIE = 'LOAD_OPERATIONS_SERIE';
export const LOAD_OPERATIONS_SERIE_SUCCESS = 'LOAD_OPERATIONS_SERIE_SUCCESS';
export const LOAD_OPERATIONS_OPERATION = 'LOAD_OPERATIONS_OPERATION';
export const LOAD_OPERATIONS_OPERATION_SUCCESS =
	'LOAD_OPERATIONS_OPERATION_SUCCESS';

//SAVE
export const SAVE_OPERATIONS_FAMILY = 'SAVE_OPERATIONS_FAMILY';
export const SAVE_OPERATIONS_FAMILY_SUCCESS = 'SAVE_OPERATIONS_FAMILY_SUCCESS';
export const SAVE_OPERATIONS_FAMILY_FAILURE = 'SAVE_OPERATIONS_FAMILY_FAILURE';

export const SAVE_OPERATIONS_OPERATION = 'SAVE_OPERATIONS_OPERATION';
export const SAVE_OPERATIONS_OPERATION_SUCCESS =
	'SAVE_OPERATIONS_OPERATION_SUCCESS';
export const SAVE_OPERATIONS_OPERATION_FAILURE =
	'SAVE_OPERATIONS_OPERATION_FAILURE';

export const SAVE_OPERATIONS_SERIE = 'SAVE_OPERATIONS_SERIE';
export const SAVE_OPERATIONS_SERIE_SUCCESS = 'SAVE_OPERATIONS_SERIE_SUCCESS';
export const SAVE_OPERATIONS_SERIE_FAILURE = 'SAVE_OPERATIONS_SERIE_FAILURE';

export const LOAD_OPERATIONS_CODES_LIST = 'LOAD_OPERATIONS_CODES_LIST';
export const LOAD_OPERATIONS_CODES_LIST_SUCCESS =
	'LOAD_OPERATIONS_CODES_LIST_SUCCESS';
export const LOAD_OPERATIONS_CODES_LIST_FAILURE =
	'LOAD_OPERATIONS_CODES_LIST_FAILURE';
