name: 'Build Application'
runs:
  using: 'composite'
  steps:
    - name: Remove package-lock.json and node_modules
      shell: bash
      run: |
        rm -f package-lock.json
        rm -rf node_modules
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: 🏗️ Installing Dependencies
      shell: bash
      run: npm i --force
    - name: 🧪 Running ESLint
      shell: bash
      run: npm run lint
    - name: 🧪 Running unit tests
      shell: bash
      run: npm run test:coverage
    - name: 🧪 Building the application
      shell: bash
      run: npm run build
