name: 'Build Application'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
    - name: 🏗️ Installing Dependencies
      shell: bash
      run: npm i --force
    - name: 🧪 Running ESLint
      shell: bash
      run: npm run lint
    - name: 🧪 Running unit tests
      shell: bash
      run: npm run test:coverage
    - name: 🧪 Building the application
      shell: bash
      run: npm run build-insee
