export const families = [
	{ id: '1', label: 'Fake Famille 1' },
	{ id: '2', label: 'Fake Famille 2' },
	{ id: '3', label: 'Fake Famille 3' },
	{ id: '4', label: 'Fake Famille 4' },
	{ id: '5', label: 'Fake Famille 5' },
	{ id: '6', label: 'Fake Famille 6' },
	{ id: '7', label: 'Fake Famille 7' },
	{ id: '8', label: 'Fake Famille 8' },
	{ id: '9', label: 'Fake Famille 9' },
	{ id: '10', label: 'Fake Famille 10' },
	{ id: '11', label: 'Fake Famille 11' },
	{ id: '12', label: 'Fake Famille 12' },
	{ id: '13', label: 'Fake Famille 13' },
];
