export const LOAD_OPERATIONS_CODES_LIST = "LOAD_OPERATIONS_CODES_LIST";
export const LOAD_OPERATIONS_CODES_LIST_SUCCESS = "LOAD_OPERATIONS_CODES_LIST_SUCCESS";
export const LOAD_OPERATIONS_CODES_LIST_FAILURE = "LOAD_OPERATIONS_CODES_LIST_FAILURE";
