export const LOAD_OPERATIONS_SIMS = "LOAD_OPERATIONS_SIMS";
export const LOAD_OPERATIONS_SIMS_SUCCESS = "LOAD_OPERATIONS_SIMS_SUCCESS";
export const LOAD_OPERATIONS_SIMS_LIST_FAILURE = "LOAD_OPERATIONS_SIMS_LIST_FAILURE";

export const SAVE_OPERATIONS_SIMS = "SAVE_OPERATIONS_SIMS";
export const SAVE_OPERATIONS_SIMS_SUCCESS = "SAVE_OPERATIONS_SIMS_SUCCESS";
export const SAVE_OPERATIONS_SIMS_FAILURE = "SAVE_OPERATIONS_SIMS_FAILURE";

export const PUBLISH_OPERATIONS_SIMS = "PUBLISH_OPERATIONS_SIMS";
export const PUBLISH_OPERATIONS_SIMS_SUCCESS = "PUBLISH_OPERATIONS_SIMS_SUCCESS";
export const PUBLISH_OPERATIONS_SIMS_FAILURE = "PUBLISH_OPERATIONS_SIMS_FAILURE";
export const DELETE_SIMS_SUCCESS = "DELETE_SIMS_SUCCESS";
