export const groups = [
	{ id: '1', label: 'Famille 1' },
	{ id: '2', label: 'Famille 2' },
	{ id: '3', label: 'Famille 3' },
	{ id: '4', label: 'Famille 4' },
	{ id: '5', label: 'Famille 5' },
	{ id: '6', label: 'Famille 6' },
	{ id: '7', label: 'Famille 7' },
	{ id: '8', label: 'Famille 8' },
	{ id: '9', label: 'Famille 9' },
	{ id: '10', label: 'Famille 10' },
	{ id: '11', label: 'Famille 11' },
	{ id: '12', label: 'Famille 12' },
	{ id: '13', label: 'Famille 13' },
];
