export const ADMIN = 'ADMIN';
export const CONCEPTS_CONTRIBUTOR = 'CONCEPTS_CONTRIBUTOR';
export const CONCEPTS_CREATOR = 'CONCEPTS_CREATOR';
export const COLLECTIONS_CREATOR = 'COLLECTIONS_CREATOR';
