FROM node:latest as builder

WORKDIR /bauhaus

COPY ./ ./

RUN yarn

RUN yarn build-insee

FROM nginx:alpine


COPY --from=builder /bauhaus/app/build /usr/share/nginx/html
COPY --from=builder /bauhaus/config/nginx.conf /etc/nginx/nginx.conf


EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
