//LOAD CLASSIFICATION
export const LOAD_CLASSIFICATION_GENERAL = "LOAD_CLASSIFICATION_GENERAL";
export const LOAD_CLASSIFICATION_GENERAL_SUCCESS = "LOAD_CLASSIFICATION_GENERAL_SUCCESS";
export const LOAD_CLASSIFICATION_GENERAL_FAILURE = "LOAD_CLASSIFICATION_GENERAL_FAILURE";

//UPDATE CLASSIFICATION
export const UPDATE_CLASSIFICATION_SUCCESS = "UPDATE_CLASSIFICATION_SUCCESS";

//LOAD CLASSIFICATION LEVELS
export const LOAD_CLASSIFICATION_LEVELS = "LOAD_CLASSIFICATION_LEVELS";
export const LOAD_CLASSIFICATION_LEVELS_SUCCESS = "LOAD_CLASSIFICATION_LEVELS_SUCCESS";
export const LOAD_CLASSIFICATION_LEVELS_FAILURE = "LOAD_CLASSIFICATION_LEVELS_FAILURE";

//LOAD A CLASSIFICATION LEVEL
export const LOAD_CLASSIFICATION_LEVEL_GENERAL = "LOAD_CLASSIFICATION_LEVEL_GENERAL";
export const LOAD_CLASSIFICATION_LEVEL_GENERAL_SUCCESS =
  "LOAD_CLASSIFICATION_LEVEL_GENERAL_SUCCESS";
export const LOAD_CLASSIFICATION_LEVEL_GENERAL_FAILURE =
  "LOAD_CLASSIFICATION_LEVEL_GENERAL_FAILURE";

//LOAD CLASSIFICATION LEVEL MEMBERS
export const LOAD_CLASSIFICATION_LEVEL_MEMBERS = "LOAD_CLASSIFICATION_LEVEL_MEMBERS";
export const LOAD_CLASSIFICATION_LEVEL_MEMBERS_SUCCESS =
  "LOAD_CLASSIFICATION_LEVEL_MEMBERS_SUCCESS";
export const LOAD_CLASSIFICATION_LEVEL_MEMBERS_FAILURE =
  "LOAD_CLASSIFICATION_LEVEL_MEMBERS_FAILURE";

//LOAD CORRESPONDENCE GENERAL

export const LOAD_CLASSIFICATION_CORRESPONDENCE_GENERAL_SUCCESS =
  "LOAD_CLASSIFICATION_CORRESPONDENCE_GENERAL_SUCCESS";

//LOAD CORRESPONDENCE ASSOCIATIONS
export const LOAD_CLASSIFICATION_CORRESPONDENCE_ASSOCIATIONS_SUCCESS =
  "LOAD_CLASSIFICATION_CORRESPONDENCE_ASSOCIATIONS_SUCCESS";

//LOAD CORRESPONDENCE ASSOCIATION
export const LOAD_CLASSIFICATION_CORRESPONDENCE_ASSOCIATION =
  "LOAD_CLASSIFICATION_CORRESPONDENCE_ASSOCIATION";
export const LOAD_CLASSIFICATION_CORRESPONDENCE_ASSOCIATION_SUCCESS =
  "LOAD_CLASSIFICATION_CORRESPONDENCE_ASSOCIATION_SUCCESS";
