export const LOAD_OPERATIONS_DOCUMENT = 'LOAD_OPERATIONS_DOCUMENT';
export const LOAD_OPERATIONS_DOCUMENT_SUCCESS =
	'LOAD_OPERATIONS_DOCUMENT_SUCCESS';
export const LOAD_OPERATIONS_DOCUMENT_FAILURE =
	'LOAD_OPERATIONS_DOCUMENT_FAILURE';

export const SAVE_OPERATIONS_DOCUMENT = 'SAVE_OPERATIONS_DOCUMENT';
export const SAVE_OPERATIONS_DOCUMENT_SUCCESS =
	'SAVE_OPERATIONS_DOCUMENT_SUCCESS';
export const SAVE_OPERATIONS_DOCUMENT_FAILURE =
	'SAVE_OPERATIONS_DOCUMENT_FAILURE';
