export const SAVE_OPERATIONS_FAMILY = 'SAVE_OPERATIONS_FAMILY';
export const SAVE_OPERATIONS_FAMILY_SUCCESS = 'SAVE_OPERATIONS_FAMILY_SUCCESS';
export const SAVE_OPERATIONS_FAMILY_FAILURE = 'SAVE_OPERATIONS_FAMILY_FAILURE';

export const LOAD_OPERATIONS_FAMILY = 'LOAD_OPERATIONS_FAMILY';
export const LOAD_OPERATIONS_FAMILY_SUCCESS = 'LOAD_OPERATIONS_FAMILY_SUCCESS';

export const LOAD_OPERATIONS_FAMILIES_LIST = 'LOAD_OPERATIONS_FAMILIES_LIST';
export const LOAD_OPERATIONS_FAMILIES_LIST_SUCCESS =
	'LOAD_OPERATIONS_FAMILIES_LIST_SUCCESS';
export const LOAD_OPERATIONS_FAMILIES_LIST_FAILURE =
	'LOAD_OPERATIONS_FAMILIES_LIST_FAILURE';
