export const SAVE_OPERATIONS_INDICATOR = 'SAVE_OPERATIONS_INDICATOR';
export const SAVE_OPERATIONS_INDICATOR_SUCCESS =
	'SAVE_OPERATIONS_INDICATOR_SUCCESS';
export const SAVE_OPERATIONS_INDICATOR_FAILURE =
	'SAVE_OPERATIONS_INDICATOR_FAILURE';

export const LOAD_OPERATIONS_INDICATOR = 'LOAD_OPERATIONS_INDICATOR';
export const LOAD_OPERATIONS_INDICATOR_SUCCESS =
	'LOAD_OPERATIONS_INDICATOR_SUCCESS';

export const LOAD_OPERATIONS_INDICATORS_LIST =
	'LOAD_OPERATIONS_INDICATORS_LIST';
export const LOAD_OPERATIONS_INDICATORS_LIST_SUCCESS =
	'LOAD_OPERATIONS_INDICATORS_LIST_SUCCESS';
export const LOAD_OPERATIONS_INDICATORS_LIST_FAILURE =
	'LOAD_OPERATIONS_INDICATORS_LIST_FAILURE';
