export const SAVE_OPERATIONS_SERIE = 'SAVE_OPERATIONS_SERIE';
export const SAVE_OPERATIONS_SERIE_SUCCESS = 'SAVE_OPERATIONS_SERIE_SUCCESS';
export const SAVE_OPERATIONS_SERIE_FAILURE = 'SAVE_OPERATIONS_SERIE_FAILURE';

export const LOAD_OPERATIONS_SERIE = 'LOAD_OPERATIONS_SERIE';
export const LOAD_OPERATIONS_SERIE_SUCCESS = 'LOAD_OPERATIONS_SERIE_SUCCESS';

export const LOAD_OPERATIONS_SERIES_LIST = 'LOAD_OPERATIONS_SERIES_LIST';
export const LOAD_OPERATIONS_SERIES_LIST_SUCCESS =
	'LOAD_OPERATIONS_SERIES_LIST_SUCCESS';
export const LOAD_OPERATIONS_SERIES_LIST_FAILURE =
	'LOAD_OPERATIONS_SERIES_LIST_FAILURE';

export const PUBLISH_OPERATIONS_SERIES = 'PUBLISH_OPERATIONS_SERIES';
export const PUBLISH_OPERATIONS_SERIES_SUCCESS =
	'PUBLISH_OPERATIONS_SERIES_SUCCESS';
export const PUBLISH_OPERATIONS_SERIES_FAILURE =
	'PUBLISH_OPERATIONS_SERIES_FAILURE';
