export const LOAD_OPERATIONS_METADATASTRUCTURE_LIST =
	'LOAD_OPERATIONS_METADATASTRUCTURE_LIST';
export const LOAD_OPERATIONS_METADATASTRUCTURE_LIST_SUCCESS =
	'LOAD_OPERATIONS_METADATASTRUCTURE_LIST_SUCCESS';
export const LOAD_OPERATIONS_METADATASTRUCTURE_LIST_FAILURE =
	'LOAD_OPERATIONS_METADATASTRUCTURE_LIST_FAILURE';

export const LOAD_OPERATIONS_SIMS = 'LOAD_OPERATIONS_SIMS';
export const LOAD_OPERATIONS_SIMS_SUCCESS = 'LOAD_OPERATIONS_SIMS_SUCCESS';
export const LOAD_OPERATIONS_SIMS_LIST_FAILURE =
	'LOAD_OPERATIONS_SIMS_LIST_FAILURE';

export const SAVE_OPERATIONS_SIMS = 'SAVE_OPERATIONS_SIMS';
export const SAVE_OPERATIONS_SIMS_SUCCESS = 'SAVE_OPERATIONS_SIMS_SUCCESS';
export const SAVE_OPERATIONS_SIMS_FAILURE = 'SAVE_OPERATIONS_SIMS_FAILURE';
