export const rangeType = {
  REPORTED_ATTRIBUTE: "REPORTED_ATTRIBUTE",
  TEXT: "TEXT",
  DATE: "DATE",
  CODE_LIST: "CODE_LIST",
  RICH_TEXT: "RICH_TEXT",
  ORGANIZATION: "ORGANIZATION",
  GEOGRAPHY: "GEOGRAPHY",
  RUBRIQUE_SANS_OBJECT: "RUBRIQUE_SANS_OBJECT",
};
