export const MODULES = {
  CONCEPT_CONCEPT: "CONCEPT_CONCEPT",
  CONCEPT_COLLECTION: "CONCEPT_COLLECTION",
  CLASSIFICATION_FAMILY: "CLASSIFICATION_FAMILY",
  CLASSIFICATION_SERIES: "CLASSIFICATION_SERIES",
  CLASSIFICATION_CLASSIFICATION: "CLASSIFICATION_CLASSIFICATION",
  OPERATION_FAMILY: "OPERATION_FAMILY",
  OPERATION_SERIES: "OPERATION_SERIES",
  OPERATION_OPERATION: "OPERATION_OPERATION",
  OPERATION_INDICATOR: "OPERATION_INDICATOR",
  OPERATION_SIMS: "OPERATION_SIMS",
  OPERATION_DOCUMENT: "OPERATION_DOCUMENT",
  STRUCTURE_STRUCTURE: "STRUCTURE_STRUCTURE",
  STRUCTURE_COMPONENT: "STRUCTURE_COMPONENT",
  CODESLIST_CODESLIST: "CODESLIST_CODESLIST",
  CODESLIST_PARTIALCODESLIST: "CODESLIST_PARTIALCODESLIST",
  DATASET_DATASET: "DATASET_DATASET",
  DATASET_DISTRIBUTION: "DATASET_DISTRIBUTION",
  DDI_PHYSICALINSTANCE: "DDI_PHYSICALINSTANCE",
  GEOGRAPHY: "GEOGRAPHY",
} as const;

export type MODULE = (typeof MODULES)[keyof typeof MODULES];

export const PRIVILEGES = {
  READ: "READ",
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  PUBLISH: "PUBLISH",
  DELETE: "DELETE",
  ADMINISTRATION: "ADMINISTRATION",
} as const;

export type PRIVILEGE = (typeof PRIVILEGES)[keyof typeof PRIVILEGES];

export const STRATEGIES = {
  ALL: "ALL",
  STAMP: "STAMP",
  NONE: "NONE",
} as const;

export type STRATEGY = (typeof STRATEGIES)[keyof typeof STRATEGIES];

export interface Privilege {
  application: MODULE;
  privileges: {
    privilege: PRIVILEGE;
    strategy: STRATEGY;
  }[];
}

export interface UserStamp {
  stamp: string;
}
