export const subGroups = [
	{ id: '1', label: 'Série 1' },
	{ id: '2', label: 'Série 2' },
	{ id: '3', label: 'Série 3' },
	{ id: '4', label: 'Série 4' },
	{ id: '5', label: 'Série 5' },
	{ id: '6', label: 'Série 6' },
	{ id: '7', label: 'Série 7' },
	{ id: '8', label: 'Série 8' },
	{ id: '9', label: 'Série 9' },
	{ id: '10', label: 'Série 10' },
	{ id: '11', label: 'Série 11' },
	{ id: '12', label: 'Série 12' },
	{ id: '13', label: 'Série 13' },
];
