// CHECK_AUTH
export const CHECK_AUTH = 'CHECK_AUTH';

// LOAD_PROPERTIES
export const LOAD_PROPERTIES = 'LOAD_PROPERTIES';
export const LOAD_PROPERTIES_SUCCESS = 'LOAD_PROPERTIES_SUCCESS';
export const LOAD_PROPERTIES_FAILURE = 'LOAD_PROPERTIES_FAILURE';

//SAVE_USER_PROPS
export const SAVE_USER_PROPS = 'SAVE_USER_PROPS';


//LOAD STAMPS
export const LOAD_STAMP_LIST = 'LOAD_STAMP_LIST';
export const LOAD_STAMP_LIST_SUCCESS = 'LOAD_STAMP_LIST_SUCCESS';
export const LOAD_STAMP_LIST_FAILURE = 'LOAD_STAMP_LIST_FAILURE';
