//LOAD FAMILLY
export const LOAD_CLASSIFICATIONS_FAMILLY_GENERAL =
	'LOAD_CLASSIFICATIONS_FAMILLY_GENERAL';
export const LOAD_CLASSIFICATIONS_FAMILLY_GENERAL_SUCCESS =
	'LOAD_CLASSIFICATIONS_FAMILLY_GENERAL_SUCCESS';
export const LOAD_CLASSIFICATIONS_FAMILLY_GENERAL_FAILURE =
	'LOAD_CLASSIFICATIONS_FAMILLY_GENERAL_FAILURE';

//LOAD FAMILLY MEMBERS
export const LOAD_CLASSIFICATIONS_FAMILLY_MEMBERS =
	'LOAD_CLASSIFICATIONS_FAMILLY_MEMBERS';
export const LOAD_CLASSIFICATIONS_FAMILLY_MEMBERS_SUCCESS =
	'LOAD_CLASSIFICATIONS_FAMILLY_MEMBERS_SUCCESS';
export const LOAD_CLASSIFICATIONS_FAMILLY_MEMBERS_FAILURE =
	'LOAD_CLASSIFICATIONS_FAMILLY_MEMBERS_FAILURE';

//UPDATE FAMILLY
export const UPDATE_CLASSIFICATIONS_FAMILLY = 'UPDATE_CLASSIFICATIONS_FAMILLY';
export const UPDATE_CLASSIFICATIONS_FAMILLY_SUCCESS =
	'UPDATE_CLASSIFICATIONS_FAMILLY_SUCCESS';
export const UPDATE_CLASSIFICATIONS_FAMILLY_FAILURE =
	'UPDATE_CLASSIFICATIONS_FAMILLY_FAILURE';

//LOAD ONE SERIES
export const LOAD_CLASSIFICATIONS_SERIES_GENERAL =
	'LOAD_CLASSIFICATIONS_SERIES_GENERAL';
export const LOAD_CLASSIFICATIONS_SERIES_GENERAL_SUCCESS =
	'LOAD_CLASSIFICATIONS_SERIES_GENERAL_SUCCESS';
export const LOAD_CLASSIFICATIONS_SERIES_GENERAL_FAILURE =
	'LOAD_CLASSIFICATIONS_SERIES_GENERAL_FAILURE';

//LOAD SERIES MEMBERS
export const LOAD_CLASSIFICATIONS_SERIES_MEMBERS =
	'LOAD_CLASSIFICATIONS_SERIES_MEMBERS';
export const LOAD_CLASSIFICATIONS_SERIES_MEMBERS_SUCCESS =
	'LOAD_CLASSIFICATIONS_SERIES_MEMBERS_SUCCESS';
export const LOAD_CLASSIFICATIONS_SERIES_MEMBERS_FAILURE =
	'LOAD_CLASSIFICATIONS_SERIES_MEMBERS_FAILURE';

//UPDATE SERIES
export const UPDATE_CLASSIFICATIONS_SERIES = 'UPDATE_CLASSIFICATIONS_SERIES';
export const UPDATE_CLASSIFICATIONS_SERIES_SUCCESS =
	'UPDATE_CLASSIFICATIONS_SERIES_SUCCESS';
export const UPDATE_CLASSIFICATIONS_SERIES_FAILURE =
	'UPDATE_CLASSIFICATIONS_SERIES_FAILURE';

//LOAD CLASSIFICATION
export const LOAD_CLASSIFICATION_GENERAL = 'LOAD_CLASSIFICATION_GENERAL';
export const LOAD_CLASSIFICATION_GENERAL_SUCCESS =
	'LOAD_CLASSIFICATION_GENERAL_SUCCESS';
export const LOAD_CLASSIFICATION_GENERAL_FAILURE =
	'LOAD_CLASSIFICATION_GENERAL_FAILURE';

//UPDATE CLASSIFICATION
export const UPDATE_CLASSIFICATION = 'UPDATE_CLASSIFICATION';
export const UPDATE_CLASSIFICATION_SUCCESS = 'UPDATE_CLASSIFICATION_SUCCESS';
export const UPDATE_CLASSIFICATION_FAILURE = 'UPDATE_CLASSIFICATION_FAILURE';

//LOAD CLASSIFICATION ITEMS
export const LOAD_CLASSIFICATION_ITEMS = 'LOAD_CLASSIFICATION_ITEMS';
export const LOAD_CLASSIFICATION_ITEMS_SUCCESS =
	'LOAD_CLASSIFICATION_ITEMS_SUCCESS';
export const LOAD_CLASSIFICATION_ITEMS_FAILURE =
	'LOAD_CLASSIFICATION_ITEMS_FAILURE';

//LOAD CLASSIFICATION LEVELS
export const LOAD_CLASSIFICATION_LEVELS = 'LOAD_CLASSIFICATION_LEVELS';
export const LOAD_CLASSIFICATION_LEVELS_SUCCESS =
	'LOAD_CLASSIFICATION_LEVELS_SUCCESS';
export const LOAD_CLASSIFICATION_LEVELS_FAILURE =
	'LOAD_CLASSIFICATION_LEVELS_FAILURE';

//LOAD A CLASSIFICATION LEVEL
export const LOAD_CLASSIFICATION_LEVEL_GENERAL =
	'LOAD_CLASSIFICATION_LEVEL_GENERAL';
export const LOAD_CLASSIFICATION_LEVEL_GENERAL_SUCCESS =
	'LOAD_CLASSIFICATION_LEVEL_GENERAL_SUCCESS';
export const LOAD_CLASSIFICATION_LEVEL_GENERAL_FAILURE =
	'LOAD_CLASSIFICATION_LEVEL_GENERAL_FAILURE';

//LOAD CLASSIFICATION LEVEL MEMBERS
export const LOAD_CLASSIFICATION_LEVEL_MEMBERS =
	'LOAD_CLASSIFICATION_LEVEL_MEMBERS';
export const LOAD_CLASSIFICATION_LEVEL_MEMBERS_SUCCESS =
	'LOAD_CLASSIFICATION_LEVEL_MEMBERS_SUCCESS';
export const LOAD_CLASSIFICATION_LEVEL_MEMBERS_FAILURE =
	'LOAD_CLASSIFICATION_LEVEL_MEMBERS_FAILURE';

//LOAD A CLASSIFICATION ITEM
export const LOAD_CLASSIFICATION_ITEM_GENERAL =
	'LOAD_CLASSIFICATION_ITEM_GENERAL';
export const LOAD_CLASSIFICATION_ITEM_GENERAL_SUCCESS =
	'LOAD_CLASSIFICATION_ITEM_GENERAL_SUCCESS';
export const LOAD_CLASSIFICATION_ITEM_GENERAL_FAILURE =
	'LOAD_CLASSIFICATION_ITEM_GENERAL_FAILURE';

//LOAD CLASSIFICATION ITEM NOTES
export const LOAD_CLASSIFICATION_ITEM_NOTES_VERSION =
	'LOAD_CLASSIFICATION_ITEM_NOTES_VERSION';
export const LOAD_CLASSIFICATION_ITEM_NOTES_VERSION_SUCCESS =
	'LOAD_CLASSIFICATION_ITEM_NOTES_VERSION_SUCCESS';
export const LOAD_CLASSIFICATION_ITEM_NOTES_VERSION_FAILURE =
	'LOAD_CLASSIFICATION_ITEM_NOTES_VERSION_FAILURE';
export const LOAD_CLASSIFICATION_ITEM_NOTES_ALL =
	'LOAD_CLASSIFICATION_ITEM_NOTES_ALL';
export const LOAD_CLASSIFICATION_ITEM_NOTES_ALL_SUCCESS =
	'LOAD_CLASSIFICATION_ITEM_NOTES_ALL_SUCCESS';
export const LOAD_CLASSIFICATION_ITEM_NOTES_ALL_FAILURE =
	'LOAD_CLASSIFICATION_ITEM_NOTES_ALL_FAILURE';

//LOAD CLASSIFICATION ITEM NARROWERS
export const LOAD_CLASSIFICATION_ITEM_NARROWERS =
	'LOAD_CLASSIFICATION_ITEM_NARROWERS';
export const LOAD_CLASSIFICATION_ITEM_NARROWERS_SUCCESS =
	'LOAD_CLASSIFICATION_ITEM_NARROWERS_SUCCESS';
export const LOAD_CLASSIFICATION_ITEM_NARROWERS_FAILURE =
	'LOAD_CLASSIFICATION_ITEM_NARROWERS_FAILURE';

//LOAD CORRESPONDENCES
export const LOAD_CLASSIFICATION_CORRESPONDENCE_LIST =
	'LOAD_CLASSIFICATION_CORRESPONDENCE_LIST';
export const LOAD_CLASSIFICATION_CORRESPONDENCE_LIST_SUCCESS =
	'LOAD_CLASSIFICATION_CORRESPONDENCE_LIST_SUCCESS';
export const LOAD_CLASSIFICATION_CORRESPONDENCE_LIST_FAILURE =
	'LOAD_CLASSIFICATION_CORRESPONDENCE_LIST_FAILURE';

//LOAD CORRESPONDENCE GENERAL
export const LOAD_CLASSIFICATION_CORRESPONDENCE_GENERAL =
	'LOAD_CLASSIFICATION_CORRESPONDENCE_GENERAL';
export const LOAD_CLASSIFICATION_CORRESPONDENCE_GENERAL_SUCCESS =
	'LOAD_CLASSIFICATION_CORRESPONDENCE_GENERAL_SUCCESS';
export const LOAD_CLASSIFICATION_CORRESPONDENCE_GENERAL_FAILURE =
	'LOAD_CLASSIFICATION_CORRESPONDENCE_GENERAL_FAILURE';

//LOAD CORRESPONDENCE ASSOCIATIONS
export const LOAD_CLASSIFICATION_CORRESPONDENCE_ASSOCIATIONS =
	'LOAD_CLASSIFICATION_CORRESPONDENCE_ASSOCIATIONS';
export const LOAD_CLASSIFICATION_CORRESPONDENCE_ASSOCIATIONS_SUCCESS =
	'LOAD_CLASSIFICATION_CORRESPONDENCE_ASSOCIATIONS_SUCCESS';
export const LOAD_CLASSIFICATION_CORRESPONDENCE_ASSOCIATIONS_FAILURE =
	'LOAD_CLASSIFICATION_CORRESPONDENCE_ASSOCIATIONS_FAILURE';

//LOAD CORRESPONDENCE ASSOCIATION
export const LOAD_CLASSIFICATION_CORRESPONDENCE_ASSOCIATION =
	'LOAD_CLASSIFICATION_CORRESPONDENCE_ASSOCIATION';
export const LOAD_CLASSIFICATION_CORRESPONDENCE_ASSOCIATION_SUCCESS =
	'LOAD_CLASSIFICATION_CORRESPONDENCE_ASSOCIATION_SUCCESS';
export const LOAD_CLASSIFICATION_CORRESPONDENCE_ASSOCIATION_FAILURE =
	'LOAD_CLASSIFICATION_CORRESPONDENCE_ASSOCIATION_FAILURE';
