//LOAD CONCEPTS
export const LOAD_CONCEPT_LIST = 'LOAD_CONCEPT_LIST';
export const LOAD_CONCEPT_LIST_SUCCESS = 'LOAD_CONCEPT_LIST_SUCCESS';
export const LOAD_CONCEPT_LIST_FAILURE = 'LOAD_CONCEPT_LIST_FAILURE';

// LOAD COLLECTION DASHBOARD LIST
export const LOAD_COLLECTION_DASHBOARD_LIST = 'LOAD_COLLECTION_DASHBOARD_LIST';
export const LOAD_COLLECTION_DASHBOARD_LIST_SUCCESS =
	'LOAD_COLLECTION_DASHBOARD_LIST_SUCCESS';
export const LOAD_COLLECTION_DASHBOARD_LIST_FAILURE =
	'LOAD_COLLECTION_DASHBOARD_LIST_FAILURE';

//LOAD CONCEPTS TO VALIDATE
export const LOAD_CONCEPT_VALIDATE_LIST = 'LOAD_CONCEPT_VALIDATE_LIST';
export const LOAD_CONCEPT_VALIDATE_LIST_SUCCESS =
	'LOAD_CONCEPT_VALIDATE_LIST_SUCCESS';
export const LOAD_CONCEPT_VALIDATE_LIST_FAILURE =
	'LOAD_CONCEPT_VALIDATE_LIST_FAILURE';

//LOAD CONCEPTS FOR SEARCH
export const LOAD_CONCEPT_SEARCH_LIST = 'LOAD_CONCEPT_SEARCH_LIST';
export const LOAD_CONCEPT_SEARCH_LIST_SUCCESS =
	'LOAD_CONCEPT_SEARCH_LIST_SUCCESS';
export const LOAD_CONCEPT_SEARCH_LIST_FAILURE =
	'LOAD_CONCEPT_SEARCH_LIST_FAILURE';

//VALIDATE CONCEPTS
export const VALIDATE_CONCEPT_LIST = 'VALIDATE_CONCEPT_LIST';
export const VALIDATE_CONCEPT_LIST_SUCCESS = 'VALIDATE_CONCEPT_LIST_SUCCESS';
export const VALIDATE_CONCEPT_LIST_FAILURE = 'VALIDATE_CONCEPT_LIST_FAILURE';

//EXPORT
export const EXPORT_CONCEPT = 'EXPORT_CONCEPT';
export const EXPORT_CONCEPT_SUCCESS = 'EXPORT_CONCEPT_SUCCESS';
export const EXPORT_CONCEPT_FAILURE = 'EXPORT_CONCEPT_FAILURE';
export const EXPORT_CONCEPT_LIST = 'EXPORT_CONCEPT_LIST';
export const EXPORT_CONCEPT_LIST_SUCCESS = 'EXPORT_CONCEPT_LIST_SUCCESS';
export const EXPORT_CONCEPT_LIST_FAILURE = 'EXPORT_CONCEPT_LIST_FAILURE';

//SEND
export const SEND_CONCEPT = 'SEND_CONCEPT';
export const SEND_CONCEPT_SUCCESS = 'SEND_CONCEPT_SUCCESS';
export const SEND_CONCEPT_FAILURE = 'SEND_CONCEPT_FAILURE';

//CREATE CONCEPT
export const CREATE_CONCEPT = 'CREATE_CONCEPT';
export const CREATE_CONCEPT_SUCCESS = 'CREATE_CONCEPT_SUCCESS';
export const CREATE_CONCEPT_FAILURE = 'CREATE_CONCEPT_FAILURE';

//UPDATE CONCEPT
export const UPDATE_CONCEPT = 'UPDATE_CONCEPT';
export const UPDATE_CONCEPT_SUCCESS = 'UPDATE_CONCEPT_SUCCESS';
export const UPDATE_CONCEPT_FAILURE = 'UPDATE_CONCEPT_FAILURE';

//DELETE CONCEPT
export const DELETE_CONCEPT = 'DELETE_CONCEPT';
export const DELETE_CONCEPT_SUCCESS = 'DELETE_CONCEPT_SUCCESS';
export const DELETE_CONCEPT_FAILURE = 'DELETE_CONCEPT_FAILURE';

//LOAD GENERAL
export const LOAD_CONCEPT_GENERAL = 'LOAD_CONCEPT_GENERAL';
export const LOAD_CONCEPT_GENERAL_SUCCESS = 'LOAD_CONCEPT_GENERAL_SUCCESS';
export const LOAD_CONCEPT_GENERAL_FAILURE = 'LOAD_CONCEPT_GENERAL_FAILURE';

//LOAD LINKS
export const LOAD_CONCEPT_LINKS = 'LOAD_CONCEPT_LINKS';
export const LOAD_CONCEPT_LINKS_SUCCESS = 'LOAD_CONCEPT_LINKS_SUCCESS';
export const LOAD_CONCEPT_LINKS_FAILURE = 'LOAD_CONCEPT_LINKS_FAILURE';

//LOAD NOTES
export const LOAD_NOTES_VERSION = 'LOAD_NOTES_VERSION';
export const LOAD_NOTES_VERSION_SUCCESS = 'LOAD_NOTES_VERSION_SUCCESS';
export const LOAD_NOTES_VERSION_FAILURE = 'LOAD_NOTES_VERSION_FAILURE';
export const LOAD_NOTES_ALL = 'LOAD_NOTES_ALL';
export const LOAD_NOTES_ALL_SUCCESS = 'LOAD_NOTES_ALL_SUCCESS';
export const LOAD_NOTES_ALL_FAILURE = 'LOAD_NOTES_ALL_FAILURE';

//LOAD COLLECTIONS
export const LOAD_COLLECTION_LIST = 'LOAD_COLLECTION_LIST';
export const LOAD_COLLECTION_LIST_SUCCESS = 'LOAD_COLLECTION_LIST_SUCCESS';
export const LOAD_COLLECTION_LIST_FAILURE = 'LOAD_COLLECTION_LIST_FAILURE';

//LOAD COLLECTIONS TO VALIDATE
export const LOAD_COLLECTION_VALIDATE_LIST = 'LOAD_COLLECTION_VALIDATE_LIST';
export const LOAD_COLLECTION_VALIDATE_LIST_SUCCESS =
	'LOAD_COLLECTION_VALIDATE_LIST_SUCCESS';
export const LOAD_COLLECTION_VALIDATE_LIST_FAILURE =
	'LOAD_COLLECTION_VALIDATE_LIST_FAILURE';

//VALIDATE COLLECTIONS
export const VALIDATE_COLLECTION_LIST = 'VALIDATE_COLLECTION_LIST';
export const VALIDATE_COLLECTION_LIST_SUCCESS =
	'VALIDATE_COLLECTION_LIST_SUCCESS';
export const VALIDATE_COLLECTION_LIST_FAILURE =
	'VALIDATE_COLLECTION_LIST_FAILURE';

//EXPORT
export const EXPORT_COLLECTION = 'EXPORT_COLLECTION';
export const EXPORT_COLLECTION_SUCCESS = 'EXPORT_COLLECTION_SUCCESS';
export const EXPORT_COLLECTION_FAILURE = 'EXPORT_COLLECTION_FAILURE';
export const EXPORT_COLLECTION_LIST = 'EXPORT_COLLECTION_LIST';
export const EXPORT_COLLECTION_LIST_SUCCESS = 'EXPORT_COLLECTION_LIST_SUCCESS';
export const EXPORT_COLLECTION_LIST_FAILURE = 'EXPORT_COLLECTION_LIST_FAILURE';

//SEND
export const SEND_COLLECTION = 'SEND_COLLECTION';
export const SEND_COLLECTION_SUCCESS = 'SEND_COLLECTION_SUCCESS';
export const SEND_COLLECTION_FAILURE = 'SEND_COLLECTION_FAILURE';

//CREATE COLLECTION
export const CREATE_COLLECTION = 'CREATE_COLLECTION';
export const CREATE_COLLECTION_SUCCESS = 'CREATE_COLLECTION_SUCCESS';
export const CREATE_COLLECTION_FAILURE = 'CREATE_COLLECTION_FAILURE';

//UPDATE COLLECTION
export const UPDATE_COLLECTION = 'UPDATE_COLLECTION';
export const UPDATE_COLLECTION_SUCCESS = 'UPDATE_COLLECTION_SUCCESS';
export const UPDATE_COLLECTION_FAILURE = 'UPDATE_COLLECTION_FAILURE';

//LOAD GENERAL
export const LOAD_COLLECTION_GENERAL = 'LOAD_COLLECTION_GENERAL';
export const LOAD_COLLECTION_GENERAL_SUCCESS =
	'LOAD_COLLECTION_GENERAL_SUCCESS';
export const LOAD_COLLECTION_GENERAL_FAILURE =
	'LOAD_COLLECTION_GENERAL_FAILURE';

//LOAD MEMBERS
export const LOAD_COLLECTION_MEMBERS = 'LOAD_COLLECTION_MEMBERS';
export const LOAD_COLLECTION_MEMBERS_SUCCESS =
	'LOAD_COLLECTION_MEMBERS_SUCCESS';
export const LOAD_COLLECTION_MEMBERS_FAILURE =
	'LOAD_COLLECTION_MEMBERS_FAILURE';

//LOAD ROLE STATUS
export const LOAD_ROLE_LIST = 'LOAD_ROLE_LIST';
export const LOAD_ROLE_LIST_SUCCESS = 'LOAD_ROLE_LIST_SUCCESS';
export const LOAD_ROLE_LIST_FAILURE = 'LOAD_ROLE_LIST_FAILURE';

//LOAD AGENT LIST
export const LOAD_AGENT_LIST = 'LOAD_AGENT_LIST';
export const LOAD_AGENT_LIST_SUCCESS = 'LOAD_AGENT_LIST_SUCCESS';
export const LOAD_AGENT_LIST_FAILURE = 'LOAD_AGENT_LIST_FAILURE';

//ADD AGENT FROM ROLE LIST
export const ADD_ROLE = 'ADD_ROLE';
export const ADD_ROLE_SUCCESS = 'ADD_ROLE_SUCCESS';
export const ADD_ROLE_FAILURE = 'ADD_ROLE_FAILURE';

//DELETE AGENT FROM ROLE LIST
export const DELETE_ROLE = 'DELETE_ROLE';
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
export const DELETE_ROLE_FAILURE = 'DELETE_ROLE_FAILURE';
