name: 'Build Documentation'
runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "pnpm"
    - name: 🏗️ Generate Astro Documentation
      shell: bash
      run: ./scripts/documentation-build.sh
    - name: 📁 Generate WebSite folder before deploying
      shell: bash
      run: ./scripts/documentation-deploy.sh
