import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const SCRIPT_PATH = fileURLToPath(import.meta.url);
const PROJECT_ROOT = resolve(dirname(SCRIPT_PATH), "..");

export const SCHEMA_PATH = resolve(
  PROJECT_ROOT,
  "src/schemas/ddi-schema.json",
);

export const OUTPUT_PATH = resolve(
  PROJECT_ROOT,
  "src/packages/modules-ddi/physical-instances/types/generated/ddi.ts",
);

// Bump when the generation logic changes so existing files are regenerated
// even if the input schema bytes are unchanged.
const SCRIPT_VERSION = "1";

interface SchemaContents {
  raw: string;
  parsed: Record<string, unknown>;
}

async function readSchema(): Promise<SchemaContents> {
  let raw = await readFile(SCHEMA_PATH, "utf-8");
  if (raw.charCodeAt(0) === 0xfeff) raw = raw.slice(1);
  return { raw, parsed: JSON.parse(raw) };
}

function wrapAsOpenApi(
  schema: Record<string, unknown>,
): Record<string, unknown> {
  const defs = (schema.$defs as Record<string, unknown> | undefined) ?? {};
  const wrapper = {
    openapi: "3.1.0",
    info: { title: "DDI 4", version: "1.0.0" },
    paths: {},
    components: { schemas: structuredClone(defs) },
  };
  const rewritten = JSON.stringify(wrapper).replaceAll(
    "#/$defs/",
    "#/components/schemas/",
  );
  return JSON.parse(rewritten);
}

function computeHash(raw: string): string {
  return createHash("sha256")
    .update(`v${SCRIPT_VERSION}\n`)
    .update(raw)
    .digest("hex");
}

const HASH_MARKER = /^\/\/ ddi-schema-hash: ([a-f0-9]{64})$/m;

async function readExistingHash(): Promise<string | null> {
  try {
    const existing = await readFile(OUTPUT_PATH, "utf-8");
    return existing.match(HASH_MARKER)?.[1] ?? null;
  } catch {
    return null;
  }
}

export interface GenerateResult {
  written: boolean;
  hash: string;
  outputPath: string;
}

export async function generateDdiTypes(): Promise<GenerateResult> {
  const { raw, parsed } = await readSchema();
  const hash = computeHash(raw);

  if ((await readExistingHash()) === hash) {
    return { written: false, hash, outputPath: OUTPUT_PATH };
  }

  const openapiDoc = wrapAsOpenApi(parsed);
  const ast = await openapiTS(openapiDoc);
  const body = astToString(ast);

  const header = [
    "// AUTO-GENERATED FILE — do not edit by hand.",
    "// Source: src/schemas/ddi-schema.json (DDI Lifecycle 4.0 RC1).",
    "// Regenerated by scripts/generate-ddi-types.ts (wired into vite.config.ts).",
    `// ddi-schema-hash: ${hash}`,
    "",
    "",
  ].join("\n");

  await mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await writeFile(OUTPUT_PATH, header + body, "utf-8");
  return { written: true, hash, outputPath: OUTPUT_PATH };
}

const invokedDirectly =
  process.argv[1] !== undefined && resolve(process.argv[1]) === SCRIPT_PATH;

if (invokedDirectly) {
  generateDdiTypes()
    .then(({ written, hash, outputPath }) => {
      const short = hash.slice(0, 12);
      const status = written ? "wrote" : "up-to-date";
      console.log(
        `[generate-ddi-types] ${status} ${outputPath} (hash ${short}…)`,
      );
    })
    .catch((err: unknown) => {
      console.error("[generate-ddi-types] failed:", err);
      process.exit(1);
    });
}
