import {
  BROADER,
  NARROWER,
  REFERENCES,
  SUCCEED,
  RELATED,
  CLOSE_MATCH,
  IS_REPLACED_BY,
} from "@sdk/constants";

export const linkTypes = {
  [BROADER]: BROADER,
  [NARROWER]: NARROWER,
  [REFERENCES]: REFERENCES,
  [SUCCEED]: SUCCEED,
  [RELATED]: RELATED,
  [CLOSE_MATCH]: CLOSE_MATCH,
  [IS_REPLACED_BY]: IS_REPLACED_BY,
} as const;
