import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import mermaid from "astro-mermaid";

// https://astro.build/config
export default defineConfig({
  base: "Bauhaus",
  trailingSlash: "always",
  integrations: [
    mermaid(),
    starlight({
      title: "Bauhaus",

      defaultLocale: "root",

      locales: {
        // English docs in `src/content/docs/en/`
        root: {
          label: "English",
          lang: "en",
        },
      },
      sidebar: [
        {
          label: "User Guide",
          items: [
            { autogenerate: { directory: "guides/user-guide" } },
          ],
        },
        {
          label: "Developer Guide",
          items: [
            // Scattered top-level files (no dedicated directory), kept manual.
            {
              label: "Getting Started",
              link: import.meta.env.BASE_URL + "guides/getting-started/",
            },

            {
              label: "Architecture",
              link: import.meta.env.BASE_URL + "guides/architecture/",
            },

            {
              label: "Conventional Commits",
              link: import.meta.env.BASE_URL + "guides/conventional_commit/",
            },
            {
              label: "Git Branch Management Strategy",
              link: import.meta.env.BASE_URL + "guides/pr_branch_strategy/",
            },
            {
              label: "Gitleaks",
              link: import.meta.env.BASE_URL + "guides/gitleaks/",
            },
            {
              label: "Roles & Permissions (RBAC)",
              link: import.meta.env.BASE_URL + "guides/rbac/",
            },
          ],
        },
        {
          label: "How-to Guides",
          items: [{ autogenerate: { directory: "guides/how-to" } }],
        },
        {
          label: "Reference",
          items: [{ autogenerate: { directory: "guides/reference" } }],
        },
        {
          label: "Module Concepts",
          collapsed: true,
          items: [
            {
              label: "Tutorial: Getting Started",
              link:
                import.meta.env.BASE_URL + "guides/getting-started-concepts/",
            },
            {
              label: "Explanation",
              items: [
                { autogenerate: { directory: "guides/concepts/explanation" } },
              ],
            },
            {
              label: "How-to Guides",
              items: [
                { autogenerate: { directory: "guides/concepts/how-to" } },
              ],
            },
            {
              label: "Reference",
              items: [
                // New in Starlight 0.39: a custom link slotted alongside
                // autogenerated links within the same `items` array.
                {
                  label: "RDF Data Model",
                  link:
                    import.meta.env.BASE_URL +
                    "guides/concepts-rdf-predicates/",
                },
                { autogenerate: { directory: "guides/concepts/reference" } },
              ],
            },
          ],
        },
        {
          label: "Module Variables",
          collapsed: true,
          items: [
            {
              label: "Explanation",
              items: [
                { autogenerate: { directory: "guides/variables/explanation" } },
              ],
            },
            {
              label: "How-to Guides",
              items: [
                { autogenerate: { directory: "guides/variables/how-to" } },
              ],
            },
            {
              label: "Reference",
              items: [
                {
                  label: "Colectica API",
                  link: import.meta.env.BASE_URL + "guides/colectica/",
                },
              ],
            },
          ],
        },
      ],
    }),
  ],
});
