export const LOAD_OPERATIONS_DOCUMENTS = 'LOAD_OPERATIONS_DOCUMENTS';
export const LOAD_OPERATIONS_DOCUMENTS_SUCCESS =
	'LOAD_OPERATIONS_DOCUMENTS_SUCCESS';
export const LOAD_OPERATIONS_DOCUMENTS_FAILURE =
	'LOAD_OPERATIONS_DOCUMENTS_FAILURE';

export const LOAD_OPERATIONS_DOCUMENT = 'LOAD_OPERATIONS_DOCUMENT';
export const LOAD_OPERATIONS_DOCUMENT_SUCCESS =
	'LOAD_OPERATIONS_DOCUMENT_SUCCESS';
export const LOAD_OPERATIONS_DOCUMENT_FAILURE =
	'LOAD_OPERATIONS_DOCUMENT_FAILURE';
