export const SAVE_OPERATIONS_OPERATION = 'SAVE_OPERATIONS_OPERATION';
export const SAVE_OPERATIONS_OPERATION_SUCCESS =
	'SAVE_OPERATIONS_OPERATION_SUCCESS';
export const SAVE_OPERATIONS_OPERATION_FAILURE =
	'SAVE_OPERATIONS_OPERATION_FAILURE';

export const LOAD_OPERATIONS_OPERATION = 'LOAD_OPERATIONS_OPERATION';
export const LOAD_OPERATIONS_OPERATION_SUCCESS =
	'LOAD_OPERATIONS_OPERATION_SUCCESS';

export const LOAD_OPERATIONS_OPERATIONS_LIST =
	'LOAD_OPERATIONS_OPERATIONS_LIST';
export const LOAD_OPERATIONS_OPERATIONS_LIST_SUCCESS =
	'LOAD_OPERATIONS_OPERATIONS_LIST_SUCCESS';
export const LOAD_OPERATIONS_OPERATIONS_LIST_FAILURE =
	'LOAD_OPERATIONS_OPERATIONS_LIST_FAILURE';
