name: GHCR
on:
  issue_comment:
    types:
      - created
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  deploy:
    name: Deploy to Github Container Registry
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, 'deploy')
    steps:
      - uses: actions/checkout@v4
      - name: Log in to ghcr.io
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build, tag and image
        run: |
          TAG=$(echo "$COMMENT" | grep -oP '^deploy\s+\K\S+')
          docker build -t ghcr.io/emmanueldemey/bauhaus:$TAG -f ./Dockerfile .
          docker push ghcr.io/emmanueldemey/bauhaus:$TAG
